[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-DFS-2016",
]

unlicensed = "deny"
copyleft = "deny"
default = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"
[[bans.skip]]
name = "toml"
