name: Release cargo-public-api

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    uses: ./.github/workflows/CI.yml

  publish:
    needs: ci
    environment:
      name: crates.io
      url: https://crates.io/crates/cargo-public-api
    runs-on: ubuntu-latest
    permissions:
      contents: write # git push
    steps:
      - uses: actions/checkout@v4

      # Figure out what tag to use
      - name: calculate version
        id: version
        run: |
          version=$(cargo read-manifest --manifest-path cargo-public-api/Cargo.toml | jq --raw-output .version)
          echo "GIT_TAG=v${version}" >> $GITHUB_OUTPUT

      # Try to cargo publish cargo-public-api. If this succeeds we will tag the
      # release. This is because we don't want to have a situation where a
      # version exists at crates.io but not as a git tag.
      - run: cargo publish -p cargo-public-api
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      # Push the tag to git.
      - name: push tag
        run: |
          git tag ${{ steps.version.outputs.GIT_TAG }}
          git push origin ${{ steps.version.outputs.GIT_TAG }}

  release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # softprops/action-gh-release
    steps:
      - uses: actions/checkout@v4

      - name: calculate version
        id: version
        run: |
          version=$(cargo read-manifest --manifest-path cargo-public-api/Cargo.toml | jq --raw-output .version)
          echo "GIT_TAG=v${version}" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b # 2022-12-09, audited by me personally
        with:
          tag_name: ${{ steps.version.outputs.GIT_TAG }}
          generate_release_notes: true
